#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI 

bspc config border_width         0
bscp config borderless_monocle   true

bspc config window_gap           5
bspc config split_ratio          0.50
bspc config gapless_monocle      true
bspc config focus_follow_pointer true


# Autostart apps
xrdb merge ~/.Xresources &
~/.config/polybar/launch.sh &
picom &
feh --bg-fill ~/Imagens/wallpapers/wall.png
sxhkd
setxkbmap
