#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI 
#bscp monitor -d 1 2 3 4 5 6

bspc config border_width         0
bscp config borderless_monocle   true

bspc config window_gap           5
bspc config split_ratio          0.50
bspc config gapless_monocle      true
bspc config focus_follow_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Autostart apps
xrdb merge ~/.Xresources &
~/.config/polybar/launch.sh &
picom &
#nitorgen --restore &
feh --bg-fill ~/Imagens/wallpapers/wall.png
sxhkd
setxkbmap
